[package]
name = "mqtt-codec"
version = "0.1.0"
authors = ["chenej <chenej@gzyitop.com>"]

[dependencies]
bytes = "*"
log = "0.3"
env_logger = "0.3"
error-chain = "*"

futures = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"

[lib]
name = "mqtt_codec"
